name: portfolio_optimization
channels:
  - conda-forge
  - pytorch
  - plotly
  - gurobi
dependencies:
  - python===3.10
  - jupyterlab
  - matplotlib
  - numpy>=1.21.6
  - pandas>=1.3.5
  - pytorch>=2.0.0
  - pytorch-lightning>=2.0.0
  - neuralforecast==1.5.0
  - plotly==5.14.1
  - gurobi==10.0.1
  - python-kaleido
  - tqdm
  - pip
  - pip:
      - nbdev
      - black
      - "ray[tune]>=2.2.0"